In [97]:
import numpy as np
A = [[1, 1, 2, 2], [2, 1, 1, 2], [2, 2, 1, 1], [1, 2, 2, 1]]
B = np.array([[1, 1, 2, 2], [2, 2, 1, 1], [2, 2, 1, 1], [1, 2, 2, 1]], dtype=np.int8)
C = np.array([
            [0, 0, 0, 0], 
            [0, 1, 0, 1], 
            [0, 0, 2, 0], 
            [0, 1, 0, 0]], dtype=np.int8)
C.tolist()

[[0, 0, 0, 0], [0, 1, 0, 1], [0, 0, 2, 0], [0, 1, 0, 0]]

## Solver

In [24]:
from duko import Duko
import numpy as np
duko = Duko(render=False)
board = duko.board.astype(np.int8)

In [95]:
# one hot encode the board
# ONE, TWO = 
# find indices of 1s and 2s
BLUE, RED = np.zeros((2, 4, 4))
BLUE[np.where(board == 1)] = RED[np.where(board == 2)] = 1
DIGITS = set(range(len(board)))
done_cols, done_rows = set(), set()

def equal_count():
    """Checks for equal count of 1s and 2s in rows and cols.
    Returns True if any changes were made."""
    changed = False

    BLUE_cols = np.sum(BLUE, axis=1)  # Summing over cols [0., 2., 0., 1.]
    cols = set(np.where(BLUE_cols == 2)[0]) - done_cols # index of filled # {1}
    for c in cols:
        done_cols.add(c)

        rows = np.where(BLUE[:, c] == 1)[0]  # [1, 3]
        left_over = DIGITS - set(rows) # {0, 2}
        RED[tuple(left_over), c] = 1
        changed = True

    
    BLUE_rows = np.sum(BLUE, axis=0)
    rows = set(np.where(BLUE_rows == 2)[0]) - done_rows
    for r in rows:
        done_rows.add(r)

        cols = np.where(BLUE[r, :] == 1)[0] 
        left_over = DIGITS - set(cols)
        RED[r, tuple(left_over)] = 1
        changed = True
    
    RED_cols = np.sum(RED, axis=0)
    cols = set(np.where(RED_cols == 2)[0]) - done_cols # index of filled # {1}
    for c in cols:
        done_cols.add(c)

        rows = np.where(RED[:, c] == 1)[0]  # [1, 3]
        left_over = DIGITS - set(rows) # {0, 2}
        BLUE[tuple(left_over), c] = 1
        changed = True

    RED_rows = np.sum(RED, axis=1)
    rows = set(np.where(RED_rows == 2)[0]) - done_rows
    for r in rows:
        done_rows.add(r)

        cols = np.where(RED[r, :] == 1)[0] 
        left_over = DIGITS - set(cols)
        BLUE[r, tuple(left_over)] = 1
        changed = True

    return changed



while equal_count():
    pass
BLUE + RED*2



array([[1., 2., 1., 2.],
       [2., 1., 2., 1.],
       [1., 2., 2., 1.],
       [2., 1., 1., 2.]])

In [86]:
BLUE
# blue_rows
# np.where(board == 1)

array([[0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [20]:
# SAVE AND LOAD configirations

# save = {str(i) : a for i, a in enumerate(configs)}  # Give them names 
configs = [[1, 0], A, B]  # Or just use a list
np.savez("duko_configs.npz", *configs)  # Save them

loaded = np.load("duko_configs.npz")
configs = loaded.values()
for kek in configs:
    print(kek)

[1 0]
[[1 1 2 2]
 [2 1 1 2]
 [2 2 1 1]
 [1 2 2 1]]
[[1 1 2 2]
 [2 2 1 1]
 [2 2 1 1]
 [1 2 2 1]]


In [6]:
# load the config from disk
config = np.loadtxt("duko_config.txt", dtype=np.int8)

[[ 9 11  9  7]
 [ 9 10  9  8]
 [ 9 10  9  8]
 [10 11  8  7]]


In [54]:
dim = A.shape[0]
for i in range(dim):
    for j in range(i, dim):
        if i != j:
            # print(i, j)
            # print(A[i])
            # print(A[j])
            # print((A[i] == A[j]))
            print((A[i] == A[j]).all())

            # print()
            print((A[:, i] == A[:, j]).all())
            # if np.all(A[i] == A[j]) \
            # or np.all(A[:, i] == A[:, j]):
            #     print("False")
print(A)

False
False
False
False
False
False
True
False
False
False
False
False
[[1 1 2 2]
 [2 2 1 1]
 [2 2 1 1]
 [1 2 2 1]]


In [15]:
dim = 4
[(x, y, a) for x in range(dim) for y in range(dim) for a in range(1, 3)]

[(0, 0, 1),
 (0, 0, 2),
 (0, 1, 1),
 (0, 1, 2),
 (0, 2, 1),
 (0, 2, 2),
 (0, 3, 1),
 (0, 3, 2),
 (1, 0, 1),
 (1, 0, 2),
 (1, 1, 1),
 (1, 1, 2),
 (1, 2, 1),
 (1, 2, 2),
 (1, 3, 1),
 (1, 3, 2),
 (2, 0, 1),
 (2, 0, 2),
 (2, 1, 1),
 (2, 1, 2),
 (2, 2, 1),
 (2, 2, 2),
 (2, 3, 1),
 (2, 3, 2),
 (3, 0, 1),
 (3, 0, 2),
 (3, 1, 1),
 (3, 1, 2),
 (3, 2, 1),
 (3, 2, 2),
 (3, 3, 1),
 (3, 3, 2)]

In [13]:
A = np.array([[1, 1, 0, 1], [1, 1, 0, 1], [1, 1, 0, 1], [1, 1, 0, 1]], dtype=np.int8)
goal = np.ones(4, dtype=np.int8) * 3
row_sum = np.sum(A, axis=1)
# CHeck if all entrees in row_sum are equal to goal
print((row_sum == goal).all())

False
