In [17]:
import numpy as np
A = [[1, 1, 2, 2], [2, 1, 1, 2], [2, 2, 1, 1], [1, 2, 2, 1]]
B = np.array([[1, 1, 2, 2], [2, 2, 1, 1], [2, 2, 1, 1], [1, 2, 2, 1]], dtype=np.int8)

In [23]:
0 == False

True

In [20]:
# SAVE AND LOAD configirations

# save = {str(i) : a for i, a in enumerate(configs)}  # Give them names 
configs = [[1, 0], A, B]  # Or just use a list
np.savez("duko_configs.npz", *configs)  # Save them

loaded = np.load("duko_configs.npz")
configs = loaded.values()
for kek in configs:
    print(kek)

[1 0]
[[1 1 2 2]
 [2 1 1 2]
 [2 2 1 1]
 [1 2 2 1]]
[[1 1 2 2]
 [2 2 1 1]
 [2 2 1 1]
 [1 2 2 1]]


In [6]:
# load the config from disk
config = np.loadtxt("duko_config.txt", dtype=np.int8)

[[ 9 11  9  7]
 [ 9 10  9  8]
 [ 9 10  9  8]
 [10 11  8  7]]


In [54]:
dim = A.shape[0]
for i in range(dim):
    for j in range(i, dim):
        if i != j:
            # print(i, j)
            # print(A[i])
            # print(A[j])
            # print((A[i] == A[j]))
            print((A[i] == A[j]).all())

            # print()
            print((A[:, i] == A[:, j]).all())
            # if np.all(A[i] == A[j]) \
            # or np.all(A[:, i] == A[:, j]):
            #     print("False")
print(A)

False
False
False
False
False
False
True
False
False
False
False
False
[[1 1 2 2]
 [2 2 1 1]
 [2 2 1 1]
 [1 2 2 1]]


In [15]:
dim = 4
[(x, y, a) for x in range(dim) for y in range(dim) for a in range(1, 3)]

[(0, 0, 1),
 (0, 0, 2),
 (0, 1, 1),
 (0, 1, 2),
 (0, 2, 1),
 (0, 2, 2),
 (0, 3, 1),
 (0, 3, 2),
 (1, 0, 1),
 (1, 0, 2),
 (1, 1, 1),
 (1, 1, 2),
 (1, 2, 1),
 (1, 2, 2),
 (1, 3, 1),
 (1, 3, 2),
 (2, 0, 1),
 (2, 0, 2),
 (2, 1, 1),
 (2, 1, 2),
 (2, 2, 1),
 (2, 2, 2),
 (2, 3, 1),
 (2, 3, 2),
 (3, 0, 1),
 (3, 0, 2),
 (3, 1, 1),
 (3, 1, 2),
 (3, 2, 1),
 (3, 2, 2),
 (3, 3, 1),
 (3, 3, 2)]

In [13]:
A = np.array([[1, 1, 0, 1], [1, 1, 0, 1], [1, 1, 0, 1], [1, 1, 0, 1]], dtype=np.int8)
goal = np.ones(4, dtype=np.int8) * 3
row_sum = np.sum(A, axis=1)
# CHeck if all entrees in row_sum are equal to goal
print((row_sum == goal).all())

False
